### ISSUE TITLE
Lora Frequency

### ISSUE THREAD

**Issue by Derek1965** [nakhonthai/ESP32APRS_LoRa#10]
Hello, I have a problem over in the UK. We use frequency 439.9125 Mhz, unfortunely your firmware, will not allow me to input the last last digit. Is there a possibality you could get your firmware to do this.  Whats happening is when we TX nothing is hearing the tracker. I would really like to use your firmware, many thanks Derek.

**Comment by nakhonthai** [comment]
It can used frequency offset for adjustment.
Frequency(Mhz)+Offset(Hz)
439.9125Mhz = 439.912Mhz+500Hz

**Comment by Derek1965** [comment]
I should have noticed that, thank you.
