### ISSUE TITLE
Support esp32 s3 xiao

### ISSUE THREAD

**Issue by samsamxu** [nakhonthai/ESP32APRS_LoRa#2]
Hi, thank you for this project. I want to know about making an Igate with only GPS and OLED screen functions, is it possible? If possible, how should I go about selecting and setting up the PlatformIO Project Configuration?
I have  a esp32s3 xiao, when I build it base on the board xiao provided, the board run, but when the igate receive any beacon,  the device will reboot. 
Here is the reboot error. Would you please help to check.

``[100575][D][main.cpp:2597] loop(): Free heap: 206.3 KB  WiFi:R7000 ,RSSI:-63 dBm ,BAT: 0.000V
[110583][E][esp32-hal-adc.c:184] __analogReadMilliVolts(): Pin 0 is not ADC pin!
[110584][D][main.cpp:2596] loop(): Task process APRS=38uS        NETWORK=6049uS  GPS=0uS         SERIAL=0uS

[110588][D][main.cpp:2597] loop(): Free heap: 206.3 KB  WiFi:R7000 ,RSSI:-63 dBm ,BAT: 0.000V
[116626][D][main.cpp:4441] taskNetwork(): INET: BG9CYN-10>APDW17,TCPIP*,qAC,T2CAEAST:!3410.02NI10854.38E#144.640MHz 2024-04-15 19:11:57

Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x403844e8  PS      : 0x00060f33  A0      : 0x80384b00  A1      : 0x3fcaaad0
A2      : 0x3fca476c  A3      : 0x3fcb8a9c  A4      : 0xbde75352  A5      : 0xb385e591
A6      : 0x00060f20  A7      : 0x00000001  A8      : 0x00000007  A9      : 0x00000004
A10     : 0x405813ed  A11     : 0x00000050  A12     : 0x3fca4790  A13     : 0x3fca47c4
A14     : 0x00060f23  A15     : 0x00000000  SAR     : 0x0000001f  EXCCAUSE: 0x0000001d
EXCVADDR: 0xbde7535e  LBEG    : 0x400556d5  LEND    : 0x400556e5  LCOUNT  : 0xfffffffc

Backtrace: 0x403844e5:0x3fcaaad0 0x40384afd:0x3fcaaaf0 0x40384c2c:0x3fcaab10 0x403783f3:0x3fcaab30 0x40378444:0x3fcaab60 0x40384fcd:0x3fcaab80 0x4204f039:0x3fcaaba0 0x4207bd19:0x3fcaabe0 0x42005a6e:0x3fcaac60 0x42009f61:0x3fcaaca0

  #0  0x403844e5:0x3fcaaad0 in remove_free_block at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_tlsf.c:206
      (inlined by) block_locate_free at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_tlsf.c:442
      (inlined by) tlsf_malloc at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_tlsf.c:849     
  #1  0x40384afd:0x3fcaaaf0 in multi_heap_malloc_impl at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/multi_heap.c:187
  #2  0x40384c2c:0x3fcaab10 in multi_heap_malloc at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/multi_heap_poisoning.c:234
      (inlined by) multi_heap_malloc at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/multi_heap_poisoning.c:223
  #3  0x403783f3:0x3fcaab30 in heap_caps_malloc_base at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_caps.c:175
      (inlined by) heap_caps_malloc_base at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_caps.c:120
  #4  0x40378444:0x3fcaab60 in heap_caps_malloc_default at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/heap/heap_caps.c:230
  #5  0x40384fcd:0x3fcaab80 in malloc at /Users/ficeto/Desktop/ESP32/ESP32S2/esp-idf-public/components/newlib/heap.c:24  
  #6  0x4204f039:0x3fcaaba0 in log_printfv at C:/Users/24993/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-uart.c:565
  #7  0x4207bd19:0x3fcaabe0 in __wrap_log_printf at /Users/ficeto/Desktop/ESP32/ESP32S2/esp32-arduino-lib-builder/components/esp-rainmaker/components/esp-insights/components/esp_diagnostics/src/esp_diagnostics_log_hook.c:426
  #8  0x42005a6e:0x3fcaac60 in pkgListUpdate(char*, char*, unsigned short, bool) at src/main.cpp:1435
  #9  0x42009f61:0x3fcaaca0 in taskNetwork(void*) at src/main.cpp:4473

ELF file SHA256: 8788694045e70f1f

Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x420deea6
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x44c
load:0x403c9700,len:0xbd8
load:0x403cc700,len:0x2a80
entry 0x403c98d0
[   284][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled
[   305][D][main.cpp:1731] setup(): Start ESP32IGate V0.1
[   316][D][main.cpp:1742] setup(): EEPROM Check 37h=37h(2616Byte)

[   317][I][esp32-hal-i2c.c:75] i2cInit(): Initialising I2C Master: sda=5 scl=6 freq=400000
[   332][D][main.cpp:1888] setup(): Free heap: 340360
[   342][E][esp32-hal-adc.c:184] __analogReadMilliVolts(): Pin 0 is not ADC pin!
[   342][D][main.cpp:2596] loop(): Task process APRS=342483uS    NETWORK=0uS     GPS=0uS         SERIAL=0uS

[   351][D][main.cpp:2597] loop(): Free heap: 273.0 KB  WiFi: ,RSSI:0 dBm ,BAT: 0.000V
[   359][D][main.cpp:4291] taskNetwork(): Task Network has been start
[   388][D][WiFiGeneric.cpp:1039] _eventCallback(): Arduino Event: 0 - WIFI_READY
[   428][V][WiFiGeneric.cpp:340] _arduino_event_cb(): STA Started
V   428][D][WiFiGeneric.cpp:1039] _eventCallback(): Arduino Event: 2 - S[ TA  _S42TA9]RT[
][WiFiGeneric.cpp:392] _arduin[ o_  e4v3en2]t_[Icb(): AP Start]e[Wdi
i[   435][D][WiFiGeneric.cpp:1039] _eventCallback(): Arduino Event: 10 - AP_START
Multi.cpp:84] addAP(): [WIFI][APlistAdd] add SSID: APRSTH
[   447][I][WiFiMulti.cpp:84] addAP(): [WIFI][APlistAdd] add SSID: R7000
[   454][I][WiFiMulti.cpp:84] addAP(): [WIFI][APlistAdd] add SSID: Mate 60 Pro
[   461][I][WiFiMulti.cpp:84] addAP(): [WIFI][APlistAdd] add SSID: NGR7000
[   467][V][WiFiGeneric.cpp:97] set_esp_interface_ip(): Configuring SoftAP static IP: 192.168.4.1, MASK: 255.255.255.0, GW: 192.168.4.254
[   482][V][WiFiGeneric.cpp:143] set_esp_interface_ip(): SoftAP: 192.168.4.1 | Gateway: 192.168.4.254 | DHCP Start: 0.0.0.0 | Netmask: 255.255.255.0
[   492][V][WiFiGeneric.cpp:190] set_esp_interface_ip(): DHCP Server Range: 192.168.4.2 to 192.168.4.12
[  4108][V][WiFiGeneric.cpp:383] _arduino_event_cb(): SCAN Done: ID: 128, Status: 0, Results: 42
[  4109][D][WiFiGeneric.cpp:1039] _eventCallback(): Arduino Event: 1 - SCAN_DONE
[  4114][I][WiFiMulti.cpp:114] run(): [WIFI] scan done
[  4118][I][WiFiMulti.cpp:119] run(): [WIFI] 42 networks found``

**Comment by nakhonthai** [comment]
Fix cash from heap memory in V0.1b
