### ISSUE TITLE
Confusing README info

### ISSUE THREAD

**Issue by lyusupov** [nakhonthai/ESP32APRS_LoRa#3]
<img width="635" alt="image" src="https://github.com/nakhonthai/ESP32APRS_LoRa/assets/5849637/9b9504de-7d83-4e57-85eb-f339f6869ebc">

<br>
<br>

1) SX1231 and SX1233 are not LoRa capable ICs
2) there is no SX12732 ICs in the Semtech LoRa products list, but the SX1272 is there.

**Comment by nakhonthai** [comment]
Thank for report
Wait for update FSK support coming soon.

**Comment by lyusupov** [comment]
https://github.com/nakhonthai/ESP32APRS_LoRa/commit/40cab42660d5a7c86b1f4d4df2d8c60fa1c0a682
