### ISSUE TITLE
Heltec Wireless Tracker Battery Voltage Sensor

### ISSUE THREAD

**Issue by PorterRyan** [nakhonthai/ESP32APRS_LoRa#5]
It would be nice to have some instructions on adding the battery voltage as a sensor. I've fiddled with the software but the voltage always outputs as 0.00V.

**Comment by Szetya** [comment]
![image](https://github.com/user-attachments/assets/fdd6990b-ee7e-4da6-b2f0-380f4a56dac8)
@nakhonthai  The ADC_CTRL PIN must be set to HIGH before measurement. 🙏😇

**Comment by nakhonthai** [comment]
OK , for Heltec HTIT-Tracker fix next version 0.2c coming soon.

**Comment by nakhonthai** [comment]
> ![image](https://private-user-images.githubusercontent.com/22783982/348516574-fdd6990b-ee7e-4da6-b2f0-380f4a56dac8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MzIwMTAsIm5iZiI6MTcyMTUzMTcxMCwicGF0aCI6Ii8yMjc4Mzk4Mi8zNDg1MTY1NzQtZmRkNjk5MGItZWU3ZS00ZGE2LWIyZjAtMzgwZjRhNTZkYWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDAzMTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZTAxYTA0MmUyM2VkYTVjMWE2NWMxNjY0N2U5NDRmYTVmN2I2YzczYWFlODZmMDhlMzVkMWJhMDAzMzc5ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.irf42y04D0JNenm-geQmUceZqP3NjXytGp1Q7XAsn9I) @nakhonthai The ADC_CTRL PIN must be set to HIGH before measurement. 🙏😇

Warning! ADC_Ctl1 on B pin transistor connected direct to GPIO(forward diode). It use input pullup mode for GPIO.

**Comment by Szetya** [comment]
> OK , for Heltec HTIT-Tracker fix next version 0.2c coming soon.

I made a few changes. 
Please see the pull request. 😇

**Comment by nakhonthai** [comment]
Update V0.2c now.

**Comment by Szetya** [comment]
> Update V0.2c now.

Thank you! :)

/off
(there were some translation warnings, could you check my commits? https://github.com/nakhonthai/ESP32APRS_LoRa/pull/8/commits
Less confusing with the warnings and a better solution for the wdt.h directive (S3 doesn't need wdt.h)
/on
