### ISSUE TITLE
HTCC-AB02S

### ISSUE THREAD

**Issue by ArKangel68** [nakhonthai/ESP32APRS_LoRa#7]
I installed on Htit-Tracher successfully, it works fine. It would be possible to install on HTCC-AB02S even with only IGATE function. Thanks 73 IW2LYS

**Comment by nakhonthai** [comment]
HTCC-AB02S Based on ASR605x CPU , not support this firmware.
This firmware support ESP XTensa LX7 and RISC-V CPU only.
